#:kivy 2.3.0

<MusicPlayer>:
    orientation: 'vertical'
    padding: 10
    spacing: 10

    
    Label:
        id: "My Music"
        font_size: 24
        size_hint_y: None
        height: 50

    ScrollView:

        GridLayout:
            cols: 1
            size_hint_y: None
            height: self.minimum_height

            spacing: 5

            Button:
                text: "Temporary Button"